################################################################################
# SqlServer Imagem Alternativa - apenas redundancia do repo oficial
################################################################################

FROM liaisonintl/mssql-server-linux:v2019
#liaisonintl/mssql-server-linux